# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
