# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='user',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='Actors',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Director',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Genre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Plot',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Released',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='Title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Writers',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbRating',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
