# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_auto_20160411_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Released',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
