# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_auto_20160411_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Released',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
