# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_auto_20160420_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Writers',
            new_name='Writer',
        ),
    ]
