# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 15:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_auto_20160424_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Poster',
            field=models.URLField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
