# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Writer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
